### PR TITLE
Refactor: extract button Toast display logic to prevent spamming 

### PR DESCRIPTION
**Pull request by Zafouche**
This is a very small PR following the what I mentioned in [this comment](https://github.com/SwEnt-Group13/Unio/pull/240#discussion_r1869928781) of PR #240:

> @Redd87 I'll add the toast in my draft https://github.com/SwEnt-Group13/Unio/pull/239. Please merge this ASAP so I can resolve the conflicts as soon as possible. Or I can pull this branch into mine, but this PR is finished anyway so you can go ahead and merge it.

I unfortunately forgot to include the Toast addition to that PR, so here it is. Note that I defined a very simple logic to prevent the toasts from showing on top of each other if the user spams the `More...` button, e.g. only one `Toast` shows up at a time. This is a logic we could use in all places where we show `Toasts` as such, and use a custom class for it, but for now this suffices for the purpose of this PR.

## Description

This PR introduces a utility mechanism to prevent the spamming of `Toast` messages in the app. The utility ensures that only one Toast can be displayed at a time, canceling the currently active Toast before showing a new one. 

## Motivation and Context

There are UI elements such as buttons that display Toast messages when clicked. A user could spam these buttons to repeatedly show Toast messages, and waste their system's resources. This PR implements a solution to mitigate this issue and ensure to Toasts do not show up one behind another at the same time when these spams occur.

### ToastUtils
- Added ToastUtils.showToast logic to cancel any currently active Toast before showing a new one.

### Various screens:
- Replaced spammable toasts with calls to the utility object.

## How has this been tested?

Wrote a unit test (ToastUtilsMockTest) to verify the functionality, e.g. that the currently active Toast is canceled before displaying a new one.

### CODE REVIEW

**Comment by Zafouche** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=SwEnt-Group13_unio&pullRequest=254) **Quality Gate failed**
> Failed conditions  [10.0% Line Coverage on New Code](https://sonarcloud.io/dashboard?id=SwEnt-Group13_unio&pullRequest=254) (required ≥ 80%)
> 
> [See analysis details on SonarQube Cloud](https://sonarcloud.io/dashboard?id=SwEnt-Group13_unio&pullRequest=254)

Alt Text

**Comment by Zafouche** [comment]
This PR will be transformed as an all-purpose utility addition for `Toasts`.

**Comment by Zafouche** [comment]
I've spent quite a bit of time searching for a solution to test Toasts through android tests, and tried implementing different ways myself. No results. Apparently, it is literally not possible to test Toasts for recent Android versions. See [this discussion](https://github.com/android/android-test/issues/803), where lots of people came to the same conclusion.

**Review by Redd87 — APPROVED** [review]
Not much to say, good job and LGTM

**Pull request merged**
