### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by FlavienVa**

### CODE REVIEW

**Review by oskar-codes — COMMENTED** [review]
This looks absolutely flawless to me. What a beautiful addition to the project. Way to go 💪 🚀

**Comment by Redd87** [comment]
While we appreciate outside contributors, I do feel that this PR is somewhat lackluster, notably, but not limited to the quantity of hardcoded strings in your ReadMe.md and your total lack of ktfmt

**Comment by FlavienVa** [comment]
> ktfmt
t'es bizarre eddy, va toucher de l'herbe

**Comment by AlouchLaBouche** [comment]
This is definitely some solid work :rocket: ! Great Job @FlavienVa, we should definitely discuss your addition to the team! Sadly I must refuse your PR as the code coverage is subpar, please write better end to end tests to test the strings :100:

**Review by armouldr — COMMENTED** [review]
This is a much needed addition to our project ;) Really makes our goals more clear and well-defined  !

**Pull request closed without merging**
