### PR TITLE
chore/theme: Add Material 3 design system theme

### PR DESCRIPTION
**Pull request by Redd87**
I also added the corresponding dependencies in the .kts, .toml and font_certs.xml files

### CODE REVIEW

**Review by armouldr — APPROVED** [review]
Great way to implement the design ! Well done eddy rashad !

**Comment by Zafouche** [comment]
> Great way to implement the design ! Well done eddy rashad !

Agreed. LGTM Mr. Rashad!

**Comment by Zafouche** [comment]
That's a lot of colors!

**Comment by leagrieder** [comment]
This is a solid PR and a crucial addition to your app. Great job on defining `Color.kt`, `Type.kt`, and `Theme.kt`—these are essential components for maintaining a clean and scalable design system. One suggestion: it would be helpful to provide a bit more detail in your PR description. For guidance, you can refer to [this template](https://github.com/thephpleague/skeleton/blob/master/PULL_REQUEST_TEMPLATE.md). Keep up the good work!

**Pull request merged**
